### ISSUE TITLE
When using the ::after psuedo-class, the quotes are removed in the compiling process which breaks the css

### ISSUE THREAD

**Issue by maddieblack** [mxenabled/cssinjs#4]
Bug replicated in this sandbox: https://codesandbox.io/s/busy-hellman-slqbg?file=/src/App.js

While building out the Breadcrumbs component and utilizing ::after, the compiler ends up removing the quotes around content which breaks the css

```
'&::after': {
        content: "/",
}
```

![Screen Shot 2021-10-08 at 7 36 51 PM](https://user-images.githubusercontent.com/24688155/136634769-8d673ee2-3b36-4efc-a793-fef1db2c526e.png)

**Comment by whiteinge** [comment]
Interesting. Thanks for the detail & sandbox! I'll work on tracking down where/why those quotes are getting removed.

If you need a quick workaround looks like you can manually add the quotes back by double-quoting. E.g.:
```
"&::after": {
        content: `"/"`,
}
```

**Comment by maddieblack** [comment]
After replacing 

`content: "/"` with `content: `"/"``, its still not working in that sandbox 🤔  Am I missing something?
